const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const login = fs.readFileSync(path.join(root, "login.html"), "utf8");
const loginScript = fs.readFileSync(path.join(root, "firebase-login.js"), "utf8");
const syncScript = fs.readFileSync(path.join(root, "firebase-sync.js"), "utf8");
const config = fs.readFileSync(path.join(root, "firebase-config.js"), "utf8");
const rules = fs.readFileSync(path.join(root, "firestore.rules"), "utf8");

assert.match(login, /id="githubBtn"/);
assert.doesNotMatch(login, /id="guestBtn"/);
assert.doesNotMatch(login, /id="email"|id="password"|loginForm|registerBtn|resetBtn/);
assert.match(login, /firebase-login\.js/);
assert.match(login, /firebase-config\.js/);
assert.match(login, /https:\/\/apis\.google\.com/);
assert.match(loginScript, /GithubAuthProvider/);
assert.match(loginScript, /signInWithPopup/);
assert.match(loginScript, /getAdditionalUserInfo/);
assert.match(loginScript, /quiz-github-username/);
assert.match(loginScript, /operation-not-supported-in-this-environment/);
assert.match(loginScript, /auth\/invalid-api-key/);
assert.match(loginScript, /window\.location\.protocol === "file:"/);
assert.doesNotMatch(loginScript, /signInWithEmailAndPassword|createUserWithEmailAndPassword|sendPasswordResetEmail|sendEmailVerification/);
assert.doesNotMatch(loginScript, /quiz-dashboard-local-mode/);
assert.match(syncScript, /window\.location\.replace\("login\.html"\)/);
assert.doesNotMatch(syncScript, /isLocalFile/);
assert.match(syncScript, /deleteAccountAndData/);
assert.match(syncScript, /reauthenticateWithPopup/);
assert.match(syncScript, /loadLeaderboard/);
assert.match(syncScript, /publishLeaderboard/);
assert.doesNotMatch(syncScript, /removeLeaderboard/);
assert.doesNotMatch(syncScript, /EmailAuthProvider|reauthenticateWithCredential|signInWithEmailAndPassword|createUserWithEmailAndPassword/);
assert.match(config, /projectId:\s*"[^\"]+"/);
assert.match(config, /window\.FIREBASE_CONFIG/);
assert.doesNotMatch(config, /serviceAccount|private_key|client_email/);
assert.match(rules, /sign_in_provider\s*==\s*"github\.com"/);
assert.doesNotMatch(rules, /email_verified/);
assert.match(rules, /match \/leaderboard\/\{userId\}/);
assert.match(rules, /allow read:\s*if isGithubUser\(\)/);

console.log("Firebase login tests passed");
